### ISSUE TITLE
How to remove that messages on console 

### ISSUE THREAD

**Issue by GGTEC** [yjg30737/pyqt-custom-titlebar-setter#2]
Testing the [pyqt-custom-titlebar-setter](https://github.com/yjg30737/pyqt-custom-titlebar-setter)

I receive that messages on console when i resize or move the window, how i can remove or stop spamming that messages ?
And thanks, you make a god job with that !!

QPainter::restore: Unbalanced save/restore
QPainter::restore: Unbalanced save/restore
QPainter::restore: Unbalanced save/restore
QPainter::restore: Unbalanced save/restore
QPainter::restore: Unbalanced save/restore
QPainter::restore: Unbalanced save/restore
QPainter::restore: Unbalanced save/restore

**Comment by yjg30737** [comment]
Thanks you. 

That message indicates that there are unbalanced number of calls to QPainter::save and QPainter::restore.

And It doesn't happen to me. 

Do you use MacOS? Can you show me the code?

That might help me figure out how to solve it

**Comment by GGTEC** [comment]
Of course!

im using w11

The code is such simple =

`from PyQt5.QtWidgets import QApplication, QWidget, QVBoxLayout
from PyQt5.QtWebEngineWidgets import QWebEngineView
from PyQt5.QtCore import QUrl, Qt
from pyqt_custom_titlebar_setter import CustomTitlebarSetter
from pyqt_style_setter import StyleSetter
from qt_sass_theme import QtSassTheme
import sys



class TextEditor(QWidget):
    def __init__(self):
        super().__init__()
        self.__initUi()

    def __initUi(self):
        lay = QVBoxLayout()        
        lay.setContentsMargins(0, 0, 0, 0)
        lay.setSpacing(0)
        
        webview = QWebEngineView()
        url = 'Path to HTML file'
        webview.load(QUrl(url))

        lay.addWidget(webview)
        
        self.setLayout(lay)


if __name__ == "__main__":
    
    app = QApplication(sys.argv)
    widget = TextEditor()
    StyleSetter.setWindowStyle(widget, theme='dark')
    g = QtSassTheme()
    g.getThemeFiles(theme='#000000')
    g.setThemeFiles(widget)
    window = CustomTitlebarSetter.getCustomTitleBarWindow(main_window=widget)
    window.show()
    sys.exit(app.exec_())`
    

But have another 'problem' or I don't know how to do this,
    
The Widget that contains the QWebEngineView does not occupy the entire space of the frame, causing the title bar to drop and there is space above and below the window, in the print screem you can understand (Ignore the close and minimize button, I use this screen in another type of framework
![BUG](https://user-images.githubusercontent.com/23065725/211345169-65451bfd-b276-400b-a10a-c2728dd0b801.png)
)

**Comment by yjg30737** [comment]
Now it might work, at least another problem you've brought up

Can't upload this to pypi as a package right now so you have to personally add code below

```python
# to maintain the maximum size intact
def event(self, e):
    if int(e.type()) == 76:
        self.setMaximumHeight(self.sizeHint().height())
    return super().event(e)
```

in the very end of the
`topTitleBarWidget.py` script in
`pyqt-top-titlebar-widget` of
`pyqt-custom-titlebar-setter`

**event()** function catches the event

**76** stands for LayoutRequest which is one of the <a href="https://doc.qt.io/qt-6/qevent.html">QEvent</a>, emit when widget layout needs to be redone.

**self.setMaximumHeight(self.sizeHint().height())** is set the maximum height to most appropriate one which can get by `sizeHint().height()`

I will upload to pypi 10~12 hrs later or maybe more than that

And.. again i've never seen those messages even in the code you provided. As a matter of fact, i'm also use Windows 11.

I wonder which Python version you use..? Mine is Python 3.10

**Comment by GGTEC** [comment]
Great, the solution worked with my code! Thank you very much.

I'm using python 3.11.0, I'm not using a Venv

**Comment by yjg30737** [comment]
Sorry for belated reply.

I used **Python 3.11.1** and **global environment** to run that and there was no message problem.

Maybe you should upgrade the Python version from 3.11.0 to 3.11.1 but this is just my guessing.

Installing the PyQt all over again is another solution of this.

```
python -m pip install PyQt5
python -m pip install PyQt5-stubs
python -m pip install PyQtWebEngine --upgrade
```

If you are using `conda` environment.. that command might differ (even though i'm using pip and conda at the same environment and there's no problem so far)

Oh, by the way, do you still have that problem?

If so, is the problem that message keep popping up really or harmful to the application? like, does that slow the app down or make it crash? That'll be huge problem.

Frankly i don't know why does that happen in your case. 😔 So only thing i can say is reinstalling the PyQt like anyone can say

Thanks

**Comment by AlexisZEMB** [comment]
Hi @yjg30737,

I know the issue has been inactive for quite a while. However, I am encountering the same messages in the terminal as @GGTEC:

QWidget::setMinimumSize: (/TopTitleBarWidget) Negative sizes (0,-1) are not possible
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QPainter::restore: Unbalanced save/restore


Even if these messages are not slowing down my application in any way, they were preventing from seeing useful debug messages from my app. I've been looking at your code and found work arounds to stop them:

- In svgLabel.py:
Comment the line 14: #painter.restore().
This modification stopped the message "QPainter::restore: Unbalanced save/restore". 

- In topTitleBarWidget.py:
Comment line 61: #self.setMinimumHeight(self.sizeHint().height())
This modification stopped the message "QWidget::setMinimumSize: (/TopTitleBarWidget) Negative sizes (0,-1) are not possible". It appears that setting a minimum size was not necessary here and does not change the behavior of the title bar nor the application. Moreover, my main window is QMainWindow class from PyQt5 (and not a PyQt5 QWidget), this might explain a strange behavior as well.


About the last message "QFSFileEngine::open: No file name specified", I haven't found yet the issue, it only appears when I setup your title bar on my application. I keep you update if I find the solution...

Thank you for your work.

Regards,

Alex

**Comment by yjg30737** [comment]
Hello, Alex !

I found how to remove those messages, that caused by SvgButton. 

There are a lot of needless packages which can just include in this package and **I will fix the issue as well as delete these packages**. Actually this was my programming style years ago 😅

**Comment by AlexisZEMB** [comment]
Hi @yjg30737 !
Thank you for your feedback and investigation! 
I'm looking forward for the updated package ;)

Alex

**Comment by yjg30737** [comment]
I fixed it. You can test it out right away ! (I've added file called "test.py" to test it better)
Console will be crystal clear.

**Comment by AlexisZEMB** [comment]
Hi! Thank you for fixing it. Is it uploaded on pip? I still have the same warning messages for now when installing the package with pip...

Thank you,

Alex

**Comment by yjg30737** [comment]
Sorry, i've forgot to upload on pip ! Yeah it's kinda emberrassing.. 😅
I will upload it in the evening of my timezone. I'm in the office and i'm not able to upload it right away.
Will do!

**Comment by yjg30737** [comment]
Just finished ! Hope it works :)

**Comment by AlexisZEMB** [comment]
Hi! Everything is solved, thank you! 
Just one last thing, on your example code the import of your custom titlebar is "from pyqt_custom_titlebar_window import CustomTitlebarWindow". However, to make it work, the correct import is now "from pyqt_custom_titlebar_window.customTitlebarWindow import CustomTitlebarWindow". Besides this, everything works fine on my side.

Thank you for your work and investigation! 🥇 

Alex

**Comment by yjg30737** [comment]
Thanks for advice. I applied it into every repos 🙂

Regards, YJG
